sudo: false
language: rust
rust:
- stable
branches:
  only:
  - master
os:
- osx
- linux
script: cargo build --release --verbose
matrix:
  fast_finish: true
deploy:
  provider: bintray
  file: .bintray.json
  on:
    tags: true
  user: bacoboy
  key:
    secure: qsmI/6aPFO4UYnvp1Nz/jiB6xk4KnxFyT3DEO4RUl3uOSeiqMttGVuVmbRm/faO2KRFKQdLhUuIX8nwi8YOb//gwdRbgmtzUg7GDcN5nbqTLhu8ie0NKLkXETgEc88dR6Gea2dOQuwZuH0ZslB/f/FTJRae1FermD2h/9vsVAaBycRRUGU+WLJD0zQblnuEBGS6Bg1hsLkbxpM/AkeMv8MTBVs1gLJSRzL6Awoyp9vNNGNy+l1POtikICnnkWwFCgafNRmjgAFHkJFX/bsJD66igYvPToB4a7M0m8vchb2PBv1Z/Lbx/PcpmnSzmn3igQLuNSR5sknTYcvCoZMhISm6Rb/6WeMWsW07+hdcw4tsbQINPSsI/00Mf+nhRtQtYTH3HEOLbdl4U3N/AMb5dbtVsWFiPdwQrlg6/1CjHxzDeDRyd/n19GK50pOY10S81lIaer5SrZ9GQh2QJXwnCGi5xQqnaV0iLtXA6MXpRm5kMXAttmebescVWuVobobYENDW8oIg5xS+VY2mwYWa+/hUFUZ6Ou3VNU57q2A0+ydvvM4hpstsgPTruxwzb8Ah83qWzARAkXk4sItRJNuv6RXM9Md2Q6Y6Plk9/Pu3prqBjnyTq00tnZ9ccM+pS5ON7mDcemA/2EyXV39UqAg6bNbePtIQt3o6AOqyKSCJLyck=
  dry-run: true
