[package]
name = "limpet"
version = "0.2.3"
authors = ["Steve Hoffman <steveh@goofy.net>"]
edition = '2018'

[dependencies]
rustc-serialize = "0.3.24"
docopt = "0.6.83"
liquid = "0.20.1"
walkdir = "2.3.1"
