name: Create new release

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    name: "Create new release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Build limpet"
        run: |
          sh ./package.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "create release"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip
