name: Create new release

on:
  push:
    branches:
      - "master"
  #   tags:
  #     - "*"

jobs:
  create-release:
    name: "Create new release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Build limpet"
        run: |
          sh ./package.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "create prerelease"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Test build"
          files: |
            *.zip
